# Generated by Django 4.1.2 on 2022-11-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
