# Generated by Django 4.1.2 on 2022-11-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
